repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 2.1.4
  hooks:
    - id: shellcheck
      # https://github.com/jumanjihouse/pre-commit-hooks/issues/82
      additional_dependencies: []
    - id: shfmt
      args: ['-i', '4']
