repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 3.0.0
  hooks:
    - id: shellcheck
      # shellcheck doesn't support ZSH
      exclude: "zsh/.zshrc"
    - id: shfmt
      args: ['-i', '4', '-bn']
      # shfmt doesn't support ZSH
      exclude: "zsh/.*"
# Using this mirror lets us use mypyc-compiled black, which is about 2x faster
- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 25.9.0
  hooks:
    - id: black
