- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.1.0
  hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 2.0.2
  hooks:
    - id: shellcheck
    - id: shfmt
