# frozen_string_literal: true

tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/cask"
tap "homebrew/core"

tap "cantino/mcfly"
tap "federico-terzi/espanso"
tap "gtback/tap"
tap "homeport/tap"
tap "martido/graph"
tap "microsoft/git"
tap "sachaos/todoist"

brew "antibody"
brew "asdf"
# /bin/bash on macOS is version 3.2.57 from 2007.
brew "bash"
brew "bat"
brew "blueutil"
brew "broot"
brew "coreutils"
brew "ctags"
brew "duf"
brew "dust"
brew "enchant"
brew "exa"
brew "fd"
brew "federico-terzi/espanso/espanso"
brew "fzf"
brew "gh"
brew "git"
brew "git-delta"
brew "git-extras"
brew "gnupg"
brew "graphviz"
brew "homeport/tap/dyff"
brew "htop"
brew "httpie"
brew "hub"
brew "jc"
brew "jid"
brew "jq"
brew "lastpass-cli"
brew "mas"
brew "mcfly"
brew "moreutils"
brew "mtr"
brew "ncdu"
brew "nnn"
brew "noti"
brew "pandoc"
brew "pinentry-mac"
brew "pipx"
brew "procs"
brew "pstree"
brew "ranger"
brew "ripgrep"
brew "sachaos/todoist/todoist"
brew "sd"
brew "shellcheck"
brew "shfmt"
brew "sk"
brew "starship"
# Needed to install some fonts
brew "subversion"
brew "switchaudio-osx"
brew "tldr"
brew "tmux"
brew "tmuxinator"
brew "trash"
brew "tree"
brew "unp"
brew "unzip"
brew "vim"
brew "watch"
brew "wget"
brew "yq"
brew "zoxide"
brew "zsh"

cask "1password"
cask "1password-cli@1"
cask "alacritty"
cask "alfred"
cask "appcleaner"
cask "bartender"
cask "clipy"
cask "dash"
cask "eloston-chromium"
cask "firefox-nightly"
cask "firefox"
cask "font-inconsolata-nerd-font"
cask "font-sauce-code-pro-nerd-font"
cask "font-source-code-pro"
cask "git-credential-manager-core"
cask "grandperspective"
cask "istat-menus"
cask "joplin"
cask "keybase"
cask "lastpass"
cask "rectangle"
cask "rocket"
cask "slack"
cask "spotify"
cask "sunsama"
cask "syncthing"
cask "toggl"
cask "vagrant"
cask "virtualbox"
cask "visual-studio-code"
cask "vlc"
cask "zoom"

mas "Amphetamine", id: 937984704
mas "Bumpr", id: 1166066070
mas "Fantastical", id: 975937182
# Do not install LastPass from the Mac App Store; it's really old; use the Cask instead.
# mas "LastPass", id: 926036361
mas "Speedtest", id: 1153157709
mas "Pocket", id: 568494494
mas "Timery", id: 1425368544
mas "Todoist", id: 585829637
