#!/bin/bash

### Date aliases
alias today="date +%F"
alias now="date +%FT%T"
alias utc.offset="date +%z"
alias utc.now="date -u +'%Y-%m-%dT%H:%M:%SZ'"

## "Improved" standard utils

# https://eza.rocks/
alias ls='eza'
alias l='eza -lFhg -m --time-style=long-iso'
alias ll='eza -l'
# https://github.com/sharkdp/bat
alias cat=bat
# https://github.com/muesli/duf
alias df=duf
# https://github.com/bootandy/dust
alias du=dust

alias version="echo -n \"VirtualBox \" && VBoxManage --version && vagrant --version && git --version && tmux -V &&  vim --version | head -1"

alias vagrant-ids="grep '.*' ~/code/**/.vagrant/machines/*/virtualbox/index_uuid"
alias lspath='f(){echo ${PATH} | tr ":" "\n"};f'
alias proxies="env | grep -i proxy"

alias git=hub
alias ip="http https://httpbin.org/ip | jq -r '.origin'"
alias td=todoist
alias tg=toggl
alias tm="tmuxinator start"
alias xo="xargs open"

# List top level npm packages (global and local)
#   (https://gist.github.com/yyx990803/6045243)
alias nlg="npm list -g --depth=0 2>/dev/null"
alias nl="npm list --depth=0 2>/dev/null"

function comm.in-both {
    comm -12 "$@"
}

function comm.only-in-first {
    comm -23 "$@"
}

function comm.only-in-second {
    comm -13 "$@"
}

zreload() {
    CONFIG_FILE=$ZDOTDIR/.zshrc
    # shellcheck source=../zsh/.zshrc
    source "$CONFIG_FILE"
    echo "Reloaded ZSH config from $CONFIG_FILE"
}
alias zr=zreload

function start() {
    op.signin
    eval "$(load-gh-token.sh)"
    ssh-add
    noti.setup
    tmux
}

function stop() {
    op signout
    unset GITHUB_TOKEN
    ssh-add -D
    noti.clear
}

# https://superuser.com/a/1246245
function pwg() {
    ENTROPY=${1:-20}

    head -c "$ENTROPY" /dev/random | base64 | tr -d '\n=+/'
    echo
}
