#!/bin/bash

export PATH="$HOME/dotfiles/bin:$HOME/bin:$HOME/.local/bin:/usr/local/sbin:$PATH"

export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"

export EDITOR=vim
export TERM=xterm-256color
export DISABLE_AUTO_TITLE='true'

export IP_RE="((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)"
export CIDR_RE="${IP_RE}/(3[0-2]|[0-2]?[0-9])"

# This is my personal GPG key, available at
# https://gregback.net/pgp/9836566B227CEF7F.asc
export KEYID=0x9836566B227CEF7F

# Tmuxinator sets GEM_HOME, which is then inherited by tmux and shells running
# inside of it. This interferes with how `asdf`-managed rubies install gems.
# - https://discourse.brew.sh/t/why-does-tmuxinator-sets-gem-home/7296
unset -v GEM_HOME
