#!/bin/bash

export PATH="$HOME/dotfiles/bin:$HOME/bin:$HOME/.local/bin:/usr/local/sbin:$PATH"

export EDITOR=vim
export TERM=xterm-256color
export DISABLE_AUTO_TITLE='true'

export WORKON_HOME="$HOME/.virtualenvs"
export PROJECT_HOME="$HOME/code"
export VIRTUAL_ENV_DISABLE_PROMPT=true

export POWERLINE=$HOME/.local/venvs/powerline-status/lib/python3.6/site-packages/powerline

export IP_RE="((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)"
export CIDR_RE="${IP_RE}/(3[0-2]|[0-2]?[0-9])"

export PYTHONSTARTUP="$HOME/.pythonstartup"

# Tmuxinator sets GEM_HOME, which is then inherited by tmux and shells running
# inside of it. This interferes with how `asdf`-managed rubies install gems.
# - https://discourse.brew.sh/t/why-does-tmuxinator-sets-gem-home/7296
unset -v GEM_HOME

export MCFLY_KEY_SCHEME=vim
export MCFLY_FUZZY=2
export MCFLY_RESULTS=50
