#!/bin/bash

export PATH="$HOME/dotfiles/bin:$HOME/bin:$HOME/.local/bin:/usr/local/sbin:$PATH"

export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"

export EDITOR=vim
export DISABLE_AUTO_TITLE='true'

export IP_RE="((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)"
export CIDR_RE="${IP_RE}/(3[0-2]|[0-2]?[0-9])"

export GITHUB_USER=gtback

# This is my personal GPG key, available at
# https://gregback.net/pgp/9836566B227CEF7F.asc
export KEYID=0x9836566B227CEF7F
