# This Brewfile is designed to be run by through `brew.compile`:
# It will fail if you run with `brew bundle install -f`

# frozen_string_literal: true

# tap repositories and their packages
tap "homebrew/bundle"

tap "homeport/tap"
brew "dyff", trusted: true

# https://github.com/martido/homebrew-graph
tap "martido/graph", trusted: true

brew "antidote"
# /bin/bash on macOS is version 3.2.57 from 2007.
brew "bash"
brew "bat"
brew "blueutil"
brew "broot"
brew "coreutils"
brew "ctags"
brew "direnv"
brew "duf"
brew "dust"
brew "enchant"
brew "eza"
brew "fd"
brew "fzf"
brew "gh"
brew "git"
brew "git-delta"
brew "git-extras"
brew "gnupg"
brew "graphviz"
brew "httpie"
brew "hub"
brew "jq"
brew "languagetool"
brew "mas"
brew "mcfly"
brew "mise"
brew "moreutils"
brew "noti"
brew "pandoc"
brew "pinentry-mac"
brew "pipx"
brew "ripgrep"
brew "sd"
brew "shellcheck"
brew "shfmt"
brew "starship"
# Needed to install some fonts
brew "subversion"
brew "switchaudio-osx"
brew "tldr"
brew "tmux"
brew "tree"
brew "unp"
brew "unzip"
brew "vim"
brew "virtualenv"
brew "virtualenvwrapper"
brew "watch"
brew "wget"
brew "ykman"
brew "yq"
brew "zoxide"
brew "zsh"

cask "1password"
cask "1password-cli"
cask "amethyst"
cask "appcleaner"
cask "bartender"
cask "claude"
cask "claude-code"
cask "dash"
cask "espanso"
cask "firefox@nightly"
cask "font-inconsolata-nerd-font"
cask "font-sauce-code-pro-nerd-font"
cask "font-source-code-pro"
cask "ghostty"
cask "git-credential-manager"
cask "istat-menus"
cask "joplin"
cask "keybase"
cask "languagetool-desktop"
cask "logitech-options"
cask "maccy"
cask "rocket"
cask "slack"
cask "spotify"
cask "sunsama"
cask "syncthing-app"
cask "tailscale-app"
cask "vagrant"
cask "visual-studio-code"
cask "vlc"
cask "yubico-authenticator"
cask "zoom"

# App Store applications
mas "Amphetamine", id: 937984704
mas "Fantastical", id: 975937182
mas "Speedtest", id: 1153157709
mas "Todoist", id: 585829637
mas "Velja", id: 1607635845

# Additional files
file ./$HOSTNAME.Brewfile
file ./Brewfile.local
