# This Brewfile is designed to be run by through `brew.compile`:
# It will fail if you run with `brew bundle install -f`

# frozen_string_literal: true

# tap repositories and their packages
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"

tap "homeport/tap"
brew "dyff"

brew "antidote"
# /bin/bash on macOS is version 3.2.57 from 2007.
brew "bash"
brew "bat"
brew "blueutil"
brew "broot"
brew "coreutils"
brew "ctags"
brew "direnv"
brew "duf"
brew "dust"
brew "enchant"
brew "eza"
brew "fd"
brew "fzf"
brew "gh"
brew "git"
brew "git-delta"
brew "git-extras"
brew "gnupg"
brew "graphviz"
brew "htop"
brew "httpie"
brew "hub"
brew "jc"
brew "jid"
brew "jq"
brew "lastpass-cli"
brew "mas"
brew "mcfly"
brew "mise"
brew "moreutils"
brew "mtr"
brew "ncdu"
brew "nnn"
brew "noti"
brew "pandoc"
brew "pinentry-mac"
brew "pipx"
brew "poetry"
brew "procs"
brew "pstree"
brew "ranger"
brew "ripgrep"
brew "sd"
brew "shellcheck"
brew "shfmt"
brew "sk"
brew "starship"
# Needed to install some fonts
brew "subversion"
brew "switchaudio-osx"
brew "tldr"
brew "tmux"
brew "tmuxinator"
brew "trash"
brew "tree"
brew "unp"
brew "unzip"
brew "vim"
brew "virtualenv"
brew "virtualenvwrapper"
brew "watch"
brew "wget"
brew "ykman"
brew "yq"
brew "zoxide"
brew "zsh"

cask "1password"
cask "1password-cli"
cask "alacritty"
cask "alfred"
cask "amethyst"
cask "appcleaner"
cask "bartender"
cask "clipy"
cask "dash"
cask "eloston-chromium"
cask "espanso"
cask "firefox"
cask "firefox@nightly"
cask "font-inconsolata-nerd-font"
cask "font-sauce-code-pro-nerd-font"
cask "font-source-code-pro"
cask "git-credential-manager"
cask "grandperspective"
cask "istat-menus"
cask "joplin"
cask "keybase"
cask "rocket"
cask "slack"
cask "spotify"
cask "sunsama"
cask "syncthing"
cask "vagrant"
# cask "virtualbox"
cask "visual-studio-code"
cask "vlc"
cask "zoom"

# App Store applications
mas "Amphetamine", id: 937984704
mas "Fantastical", id: 975937182
mas "LastPass", id: 926036361
mas "Pocket", id: 568494494
mas "Speedtest", id: 1153157709
mas "Timery", id: 1425368544
mas "Todoist", id: 585829637
mas "Velja", id: 1607635845

# Additional files
file ./$HOSTNAME.Brewfile
file ./Brewfile.local
